dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/metkit
  pybind/pybind11@v2.13.6
dependency_branch: develop
cmake_options: -DENABLE_DUMMY_DAOS=ON -DENABLE_PYTHON_ZARR_INTERFACE=ON
parallelism_factor: 8
python_version: 3.11
python_requirements: requirements.txt