dependencies: |
  ecmwf/ecbuild
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/metkit
dependency_branch: develop
cmake_options: -DENABLE_DUMMY_DAOS=ON
parallelism_factor: 8
python_version: 3.11
python_requirements: requirements.txt