apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    :80 {
    	log {
    		level DEBUG
    		output stdout
    		format console
    	}
    	encode {
    		match {
    			header Content-Type application/octet-stream
    		}
    		zstd best
    	}
    	reverse_proxy localhost:5000
    }
