apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namespace }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: z3fdb
  template:
    metadata:
      labels:
        app: z3fdb
    spec:
      containers:
      - name: {{ .Values.image.z3fdb.name }}
        image: {{ .Values.image.z3fdb.repository}}:{{ .Values.image.z3fdb.tag }}
        args: ["--fdb-config=/etc/fdb/fdb.config"]
        env:
          - name: FDB_DEBUG
            value: "1"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: z3fdb-web-volume
          mountPath: /etc/fdb/fdb.config
          subPath: fdb-config # Mounts the ConfigMap data as a single file
      - name: caddy
        image: eccr.ecmwf.int/kkratz/caddy:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile # Mounts the ConfigMap data as a single file
      volumes:
      - name: z3fdb-web-volume
        configMap:
          name: {{ .Values.namespace }}-config
      - name: caddyfile
        configMap:
          name: {{ .Values.namespace }}-caddy-config
