apiVersion: v1
kind: Service
metadata:
  name: z3fdb-web-service
  namespace: z3fdb-dev
spec:
  type: NodePort # Or NodePort for simpler Minikube access
  selector:
    app: z3fdb
  ports:
  - port: 80
    targetPort: 80
    name: http
